info:
  app:
    name: Short Me Application
    description: An URL shortener API built with Spring Boot, Thymeleaf and MongoDB
    source: https://github.com/mbalves/shortme
server:
  port: ${PORT:80}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/shortme}